language: ruby
rvm:
  - 1.9.3
  - ree
  - jruby-18mode
  - 2.0.0
gemfile:
  - gemfiles/Gemfile-rails.3.1.x
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - carlos@plataformatec.com.br
    - rafael.franca@plataformatec.com.br
